AWSTemplateFormatVersion: 2010-09-09
Description: Test Template

Resources: 

  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Join ["", ["s3-",!Ref "AWS::AccountId",testingbucket]]